import * as raw_businesses from '../data/IL_minified.json';
import * as raw_edges from '../data/IL_edges.json'
import * as raw_checkin_map from '../data/IL_checkin_stat_map.json';
import * as raw_category_map from '../data/IL_categories_stat.json';

export interface BusinessNode {
    business_id: string,
    name: string,
    address: string,
    city: string,
    state: string,
    postal_code: string,
    lat: number,
    lng: number,
    longitude?: number,
    latitude?: number,
    stars: number,
    review_count: number,
    categories: Array<string>,
    links?: Array<google.maps.Polyline>,

    // Generated by d3 force simulation
    x?: number,
    y?: number,
}

export interface Edge {
    src: string,
    dst: string,
    data: Array<string>,
    source: BusinessNode,
    target: BusinessNode,
}

// raw_businesses.forEach(d => {
//     d.lat = d.latitude;
//     d.lng = d.longitude;
//     delete d.latitude;
//     delete d.longitude;
// })

export interface category{
    name: string,
    count: number,
}

export interface CheckinStat {
    day: string,
    hour: string,
    count: number,
}

export interface CheckinData {
    business_id: string,
    date: Array<string>,
    stat: Array<CheckinStat>,
}


export let businesses = raw_businesses as Array<BusinessNode>;
export let edges = (raw_edges as Array<Edge>).filter(d => d.data.length >= 7);
export let checkin_map = raw_checkin_map as { [business_id: string]: CheckinData };
export let category_map = raw_category_map as {[key: string]: number};
